# fly.toml app configuration file generated for photoshare on 2023-09-11T17:44:50+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "photoshare"
primary_region = "waw"


[env]
  POSTGRES_USER="ycrymnbx"
  POSTGRES_PASSWORD=""
  POSTGRES_DOMAIN="snuffleupagus.db.elephantsql.com"
  POSTGRES_PORT=5432
  POSTGRES_DB_NAME="ycrymnbx"
  POSTGRES_PATH="postgresql+psycopg2://ycrymnbx:R76JH9HLrLwq6CcGfkXPpFc-PEvBcCzS@snuffleupagus.db.elephantsql.com:5432/ycrymnbx"

  EMAIL_USERNAME="webba1065@meta.ua"
  EMAIL_PASSWORD=""
  EMAIL_FROM="webba1065@meta.ua"
  EMAIL_PORT=465
  EMAIL_SERVER="smtp.meta.ua"
  EMAIL_FROM_NAME="Examplemail"

  SECRET_ACCESS_KEY=""
  SECRET_REFRESH_KEY=""
  SECRET_EMAIL_KEY=""

  ALGORITHM="HS256"

  REDIS_HOST="195.201.150.230"
  REDIS_PORT=6379
  REDIS_PASSWORD=""

  CLOUDINARY_NAME=""
  CLOUDINARY_API_KEY=""
  CLOUDINARY_API_SECRET=""

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
